### ISSUE TITLE
stupid "2K Visits!" is overlapping Flag Counter

### ISSUE THREAD

**Issue by WinNT50** [WinNT50/2003page.ga#2]
![image](https://user-images.githubusercontent.com/54199622/65095677-e0d22380-d9ca-11e9-876e-792ed4ee8fb9.png)
bruh just fix it by adding few `<br>` or something

**Comment by TLWXPUser** [comment]
Fixed.

**Comment by WinNT50** [comment]
closed as xpuser just removed it

**Comment by TLWXPUser** [comment]
ooo
